# Generated by Django 4.0.4 on 2022-05-30 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='private individual', max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(default='not available', max_length=14),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='not available', max_length=14),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(default='not set', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sales_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='support',
            field=models.ForeignKey(default='not set', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='support_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
