# Generated by Django 4.0.4 on 2022-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_sales_contact_alter_event_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
