# Generated by Django 4.0.4 on 2022-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_contract_object'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_client'),
        ),
    ]
